version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ../:/var/www
    tty: true
    container_name: 'f_app'
    environment:
      - WEB_CONFIG=${APP_WEBC}
      - MYSQL_HOST=${APP_MH}
      - MYSQL_DB=${APP_MDB}
      - MYSQL_USR=${APP_MU}
      - MYSQL_PWD=${APP_MP}
      - REDIS_HOST=${APP_RH}
      - MAIL_SERVER=${APP_MAILS}
      - MAIL_USERNAME=${APP_MAILU}
      - MAIL_PASSWORD=${APP_MAILP}
      - MAIL_SENDER=${APP_SENDER}

  server:
    build:
      context: ./
      dockerfile: server.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    container_name: 'f_server'
    ports:
      - 8000:80

  database:
    image: daocloud.io/mysql:5.7.4
    volumes:
      - dbdata:/var/lib/mysql
    container_name: 'f_db'

  redis:
    image: daocloud.io/library/redis:4.0.10-alpine
    command: redis-server --appendonly yes
    container_name: 'l_redis'

volumes:
  dbdata: